### ISSUE TITLE
Epic games launcher and Mac OS?

### ISSUE THREAD

**Issue by AndreLouisIssa** [tr4wzified/HadesUltrawideGUI#2]
Skimming the code it does seem to depend on windows and steam.

**Comment by tr4wzified** [comment]
I'll have a look to see if I can compile a build for Linux at least, that's supported by .NET 5. I'm not sure about macOS but I'll investigate :)

**Comment by tr4wzified** [comment]
Also Epic shouldn't be that hard to support considering the underlying library already supports it, I'll have a look tomorrow

**Comment by tr4wzified** [comment]
Epic Game Store is now supported! 

As for macOS - I personally don't really care about it, that and an ultrawide monitor makes for an extreme niche plus I don't have the hardware to test it. After them giving a big middle finger to game devs by dropping 32 bit support the gaming scene will likely decline even further anyway, I'm open to PRs but I'm not interested in doing the work myself.
